### ISSUE TITLE
LCD backlight setting 255 is not brightest

### ISSUE THREAD

**Issue by mthuurne** [mthuurne/opendingux-kernel#6]
$ echo 254 > /sys/class/backlight/pwm-backlight/brightness

Makes the backlight very bright.

$ echo 255 > /sys/class/backlight/pwm-backlight/brightness

Makes the backlight far less bright than 254 does; approximately the same level as 80.

Tested on A320 with kernel from jz-2.6.35 branch.

**Comment by mthuurne** [comment]
Still happens with jz-2.6.36 branch.

**Comment by pcercuei** [comment]
This bug seems to add another one. When staying at brightness 255 for too long, the screen slowly starts to flash, until the kernel become really unstable and kill the network (probably a power related issue).

**Comment by mthuurne** [comment]
I fixed this on jz-2.6.37 a few days ago. It seems to be a strange hardware property, which I worked around by decreasing the period for the PWM.
