### ISSUE TITLE
doublebuf issues with tv-out mode

### ISSUE THREAD

**Issue by zear** [mthuurne/opendingux-kernel#9]
The SDL applications compiled with SDL_DOUBLEBUF seem to have a problem with updating the screen when ran on a TV screen via the tv-out mode.
This issue results in only every second screen update being drawn on the TV screen.
It is especially noticable in gmenu2x. Gmenu2x is programmed to update the screen only if a keypress is registered. This bug results in the TV screen being refreshed every two key presses instead. A user will notice this as the menu selection "jumping" from one icon to another icon distanced 2 spaces away, leaving an icon in between unselected.

This sketch presents the described behaviour in gmenu2x.
Lines numbered as "1)", "2)", "3)" represent the visual situation of the screen between the keypresses, with "[x]" representing the icons and "> <" representing the current menu selection.

A proper behaviour:
1)  >[1]< [2] [3]
2)  [1] >[2]< [3]
3) [1] [2] >[3]<

A behaviour via tv-out:
1) >[1]< [2] [3]
2) >[1]< [2] [3]
3) [1] [2] >[3]<

So far I was able to confirm this bug occuring only in gmenu2x, but for applications using timer based screen updates, this issue might be noticable as a visual framedrop by half instead.

A workaround for this issue is to compile the SDL apps without SDL_DOUBLEBUF screen flag.

**Comment by mthuurne** [comment]
The double buffering code was written by me when we only had internal screen support (SLCD mode). The TV-out support (LCD mode) was written by Uli and merged by me. However, neither of us wrote code to support double buffering in LCD mode. Therefore the first frame buffer page (yoffset=0) is displayed all the time on the TV, while writing occurs in both pages (yoffset=0/240).

**Comment by zear** [comment]
Bug was fixed long time ago.
